### PR TITLE
Add  information about using RELX_REPLACE_OS_VARS

### PR DESCRIPTION
**Pull request by mfeckie**
Currently this isn't mentioned in the guide, but would be useful for reference.

### CODE REVIEW

**Comment by mfeckie** [comment]
Actually, following this, it doesn't seem to work. Even with it set in `.profile`.  Weirdly, I can ssh into the box and run without having to explicitly set `RELX...` and it works fine, but from edeliver deploys it doesn't seem to be respected.  I can't understand why because it seems like it should.

I've hacked together something that works for me, here, https://github.com/mfeckie/edeliver/commit/19f75e199d2ed34d8c4e99013802ca9792ccfa6c

But it would be good to figure out why it didn't work before.

Feel free to close this conversation at your leisure if it's not helpful

**Comment by bharendt** [comment]
Thanks for adding that information to the readme. Setting `RELX_REPLACE_OS_VARS` in the `~/.profile` is the right way and should actually work. That file [is sourced](https://github.com/mfeckie/edeliver/blob/19f75e199d2ed34d8c4e99013802ca9792ccfa6c/libexec/erlang#L828) for each edeliver command on the build and deploy hosts. You can test that by executing that commands directly on your deploy host using ssh, e.g. like this:
```bash
ssh deploy-user@deploy-host "source ~/.profile && echo \"RELX_REPLACE_OS_VARS is set to $$RELX_REPLACE_OS_VARS\""
```
If that is correct, you should verify, that this variable is also exported, otherwise it will not be forwarded to subshells or subcommands.

**Comment by mfeckie** [comment]
Great, thanks for the feedback.  Turns out I'd set it, but forgot to export it!  whoops.

**Comment by bharendt** [comment]
👍 Do you like to add that to the readme?

**Comment by mfeckie** [comment]
Sounds good, I've tweaked the wording so hopefully it makes things pretty clear.

**Comment by bharendt** [comment]
Thank you!

**Pull request merged**
