### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dustinfarris**
Removing some of the fanfare and a little proofreading.  This makes it more readable IMO.  If accepted I will do this to the entire document.

### CODE REVIEW

**Comment by bharendt** [comment]
Yes, please go ahead.

**Comment by dustinfarris** [comment]
@bharendt I think this is good for a first pass.

**Comment by dustinfarris** [comment]
@bharendt are there any changes you would like me to make?

**Comment by mk** [comment]
Hey @dustinfarris, thanks so much, these changes look great! If you have the time, could you please merge master or rebase? I'll merge your PR right after.

If you want to continue working on this, we'd also love to add you to the project. Just let me know. Thanks again!

**Comment by dustinfarris** [comment]
Hi @mk, yes I'd love to be added to edeliver.  Thanks for the offer.

I've rebased this PR.  Should be good to go.

**Comment by mk** [comment]
@dustinfarris great, thank you! I've invited you to edeliver. Maybe we should open an edeliver slack to discuss plans and help users there next.

**Comment by dustinfarris** [comment]
@mk got the invite!  I've been hanging out in #deployment in https://elixir-lang.slack.com/ a lot of folks there are using edeliver.

**Comment by mk** [comment]
@dustinfarris seems like we missed that until now, see you there 👋🏻

**Comment by vysakh0** [comment]
@dustinfarris Thank you! The updated README shows all the hidden gems of `edeliver` in one go.

**Pull request merged**
