### PR TITLE
Compile before release

### PR DESCRIPTION
**Pull request by aaronjensen**
exrm 1.0.0 seems to require we compile ourselves.

### CODE REVIEW

**Comment by bharendt** [comment]
and that seems to change again in the next exrm version 1.0.0-rc7 (https://github.com/bitwalker/exrm/commit/4b781afe6e5caf0c7f4493671009cc1b6519dbf3) ... and was not necessary on rc-4 or rc-5. we should maybe add then the compile task depending on the exrm version.

**Comment by aaronjensen** [comment]
I tried that version, it still seemed to fail w/o the mix compile

**Comment by bharendt** [comment]
actually I would also prefer the idea that the release task requires __explicitly to compile__ the sources __before generating the release__. what do you think @bitwalker? 
__similar to the behaviour__, that e.g. the `mix compile` task also does not fetch the dependencies automatically, __but fails__ if they are not up to date / available.
__edeliver__ could then also __decide__ a little better - e.g. if the command line option `--skip-mix-clean` is passed by the user - whether to __recompile__ all sources __or__ use an __incremental__ build for faster deployments. 
and it might be another evidence for requiring an explicit `compile` that, __depending on the type of application__ (e.g. a phoenix web application),  __"compilation"__ could also __include other additional steps__ like generating resources or assets which might also not be covered by an "automatic compilation" by exrm just before the release generation.

**Comment by mk** [comment]
I'm also in favor of putting compile back in for now. Possibly with an option to skip it with '--skip-compile'.

**Comment by bitwalker** [comment]
@bharendt I've added back in the implicit compilation because it seemed to cause more trouble than it was worth by removing it. Mix itself is a bit inconsistent as to when it will implicitly compile for you, as it only requires explicit compilation when `build_embedded: true`, which is true by default when `MIX_ENV=prod`. So while it's consistent about when it requires it, from the perspective of users it may feel a strange to have mix auto compile your project during development and then suddenly require explicit compilation when you change environment. So after removing implicit compilation from exrm and having half a dozen issues opened due to the change, I added it back in.

Mix builds are incremental by default, but if for instance someone is releasing a Phoenix application, then yes, they will need to know to trigger things like `mix phoenix.digest` themselves. One can always alias compile in their project to trigger both tasks, but that's always been something outside of the scope of exrm. I agree in general that the more explicit you are with these things, the better, but at least in the case of exrm, not compiling by default was more of a surprise than the inverse.

**Comment by bharendt** [comment]
@bitwalker: thanks for the explanation and the detailed information. I also think it makes sense, that exrm behaves consistently for every build environment. And it's even more handy when building releases locally, if you don't have to compile before. 
For __edeliver it has no negative effects__, if exrm compiles implicitely like it did before. But I will still __merge this pull request__ to be able to provide compatibility with the exrm versions which behave differently. And as long as `Mix.Project.compile(args)` from https://github.com/bitwalker/exrm/commit/4b781afe6e5caf0c7f4493671009cc1b6519dbf3 does not recompile everything, the __overhead of duplicate invocation__ of mix compile __is negligible__.

**Comment by bitwalker** [comment]
@bharendt Sounds good to me :). And to answer your question, `Mix.Project.compile` will do the same as `mix compile`, i.e. incremental compilation. So you should be good to go.

**Pull request merged**
